{% set name = "wails" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wailsapp/wails/archive/v{{ version }}.tar.gz
  sha256: b070be6f9ac1e74f748cf68acc4a774d4f392d4a0992ea4967c73d4990b8b43f

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - wails --help

about:
  home: https://github.com/wailsapp/wails
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Create beautiful applications using Go
  dev_url: https://github.com/wailsapp/wails

extra:
  recipe-maintainers:
    - danielnachun
