{% set name = "wails" %}
{% set version = "2.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wailsapp/wails/archive/v{{ version }}.tar.gz
  sha256: 864b53f22ca98ed17e456b352ec4691cfc2105bdcb23e87df8f826035b08d8c0

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - wails --help

about:
  home: https://github.com/wailsapp/wails
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Create beautiful applications using Go
  dev_url: https://github.com/wailsapp/wails

extra:
  recipe-maintainers:
    - danielnachun
