{% set name = "wails" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wailsapp/wails/archive/v{{ version }}.tar.gz
  sha256: 3dbdf683ce67968c1319436950e6da1f27e6d64802d477105fc4d7a60be19860

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - wails --help

about:
  home: https://github.com/wailsapp/wails
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Create beautiful applications using Go
  dev_url: https://github.com/wailsapp/wails

extra:
  recipe-maintainers:
    - danielnachun
