schema_version: 1

context:
  version: "2.15.0"

package:
  name: wails
  version: ${{ version }}

source:
  url: https://github.com/wailsapp/wails/archive/v${{ version }}.tar.gz
  sha256: 4c865cbd5ab81401cf4557e54dfe517efc90d29980ccdaa54178b426fdd6d4a3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - wails --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Create beautiful applications using Go
  homepage: https://github.com/wailsapp/wails
  repository: https://github.com/wailsapp/wails

extra:
  recipe-maintainers:
    - danielnachun
