schema_version: 1

context:
  version: "2.12.0"

package:
  name: wails
  version: ${{ version }}

source:
  url: https://github.com/wailsapp/wails/archive/v${{ version }}.tar.gz
  sha256: bfc663dd01f762c5524006d945616c5ce361055fa649ebc3b1ae2a16247d8fee

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - wails --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Create beautiful applications using Go
  homepage: https://github.com/wailsapp/wails
  repository: https://github.com/wailsapp/wails

extra:
  recipe-maintainers:
    - danielnachun
