schema_version: 1

context:
  version: "2.13.0"

package:
  name: wails
  version: ${{ version }}

source:
  url: https://github.com/wailsapp/wails/archive/v${{ version }}.tar.gz
  sha256: 08b8135f6dce18be6016046aa8e75607e998f4f4687154f7d9ebb1bb03666756

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - wails --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Create beautiful applications using Go
  homepage: https://github.com/wailsapp/wails
  repository: https://github.com/wailsapp/wails

extra:
  recipe-maintainers:
    - danielnachun
